language: generic
jobs:
  include:
    - os: linux
      dist: trusty
#    - os: osx
#      osx_image: xcode10.3

addons:
  apt:
    packages:
    - p7zip-full
  ssh_known_hosts:
    - 127.0.0.1

env:
  global:
    - LOCAL_MODE=1
    - LICENSE=opensource
    - BUILD_NUMBER=0
    - VERSION=v5.13.1-victron
    - IFW_GIT_URL=https://github.com/qtproject/installer-framework.git
    - IFW_GIT_VERSION=3.1
    - IFW_QT_SRC_PKG=http://download.qt.io/official_releases/qt/5.12/5.12.5/single/qt-everywhere-opensource-src-5.12.5.tar.xz
    - IFW_STATIC_QT_BIN_PKG=
    - IFW_DYNAMIC_QT_BIN_PKG=
    - ENABLE_TESTS=false
    - SIGNING_SERVER=
    - SIGNING_PASSWORD=
    - SIGNING_IDENTITY=
    - SIGNING_FLAGS=
    - HOMEBREW_NO_AUTO_UPDATE=1
    - IFW_QT_EXTRA_CONFIGURE_OPTIONS="-silent"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install p7zip ; fi

script:
  - mkdir installers
  - export LOCAL_INSTALLER_DIR=$PWD/installers
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TARGET_ENV=mac-clang-10.11-x64 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export IFW_OPENSSL_DIR=/usr/local/opt/openssl ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TARGET_ENV=linux-g++ ; fi
  - python qtsdk/packaging-tools/build_wrapper.py -c ifw -l $LICENSE -b $BUILD_NUMBER -e $TARGET_ENV

